name: CI/CD for DigitalOcean Kubernetes

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for this job

    steps:
    # Step 1: Check out code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker build environment
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    # Step 3: Log in to DigitalOcean's container registry
    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_USERNAME }}  # Store your username in GitHub Secrets
        password: ${{ secrets.DO_TOKEN }}  # Store your DigitalOcean API token in GitHub Secrets

    # Step 4: Build and push Docker image to DOCR
    - name: Build and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t registry.digitalocean.com/devopsolo/your-image-name:${{ github.sha }} .
        echo "Pushing Docker image..."
        docker push registry.digitalocean.com/devopsolo/your-image-name:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this step runs after the build step

    steps:
    # Step 1: Checkout code again
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install doctl
    - name: Install doctl
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.93.0/doctl-1.93.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin

    # Step 3: Authenticate with DigitalOcean
    - name: Authenticate with DigitalOcean
      run: doctl auth init -t ${{ secrets.DO_TOKEN }}

    # Step 4: Set up Kubernetes configuration
    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

    # Step 5: Deploy to DigitalOcean Kubernetes Cluster
    - name: Deploy to Kubernetes
      run: |
        # Save kubeconfig from DO cluster
        doctl kubernetes cluster kubeconfig save $(doctl kubernetes cluster list --format ID --no-header)
        
        # Update the deployment with new image
        kubectl set image deployment/my-app-deployment my-app-container=registry.digitalocean.com/devopsolo/your-image-name:${{ github.sha }}
        
        # Verify the rollout
        kubectl rollout status deployment/my-app-deployment
