name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean registry
        run: echo "${{ secrets.DO_TOKEN }}" | docker login registry.digitalocean.com -u "${{ secrets.DO_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t registry.digitalocean.com/devopsolo/your-image-name:latest .

      - name: Push Docker Image
        run: docker push registry.digitalocean.com/devopsolo/your-image-name:latest
